yatube/about/urls.py
from django.urls import path

from about import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow',
        views.profile_unfollow,
        name='profile_unfollow'
    )
]

yatube/yatube/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
]

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.extend(static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    ),)
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст',
        help_text='Заполните текст публикации',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Укажите автора публикации',
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Название группы, к которой относится публикация'
    )

    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
        help_text='Загрузите картинку'
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

    def __str__(self) -> str:
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        db_index=True,
        verbose_name='Название',
        help_text='Название группы, к которой относится публикация',
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Слаг',
        help_text='Уникальный фрагмент URL-адреса',
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Укажите подробное описание группы',
    )

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self) -> str:
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Ссылка на публикацию'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Напишите текст комментария'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата комментария'
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self) -> str:
        return f'Комментарий от {self.author}'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = (
            models.UniqueConstraint(
                fields=('user', 'author'), name='unique_together')
        )

    def __str__(self) -> str:
        return f'{self.user} подписан(-а) на {self.author}'

yatube/posts/forms.py
from django import forms

from posts.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )

yatube/posts/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.cache import cache_page
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.conf import settings as s

from posts.models import Group, Post, Follow, User
from posts.forms import PostForm, CommentForm


@cache_page(s.TIME_CACHE, key_prefix='index_page')
def index(request):
    template = 'posts/index.html'
    title = 'Последние обновления на сайте'
    description = 'Добро пожаловать на главную страницу Yatube'
    posts_lists = Post.objects.all()
    paginator = Paginator(posts_lists, s.NUMBER_SHOW)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'title': title,
        'description': description
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts_lists = group.posts.all()
    paginator = Paginator(posts_lists, s.NUMBER_SHOW)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'group': group,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts_lists = author.posts.select_related('author')
    post_count = posts_lists.count()
    paginator = Paginator(posts_lists, s.NUMBER_SHOW)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    title = f'Профиль пользователя {username}'
    following = (
        request.user.is_authenticated
        and author.following.filter(user=request.user).exists()
    )
    followers = Follow.objects.filter(author=author).count()
    context = {
        'post_count': post_count,
        'author': author,
        'title': title,
        'page_obj': page_obj,
        'following': following,
        'followers': followers
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, id=post_id)
    post_count = post.author.posts.count()
    followers = post.author.following.count()
    title = f'Публикация {post}'
    comments = post.comments.all()
    form = CommentForm(request.POST or None)
    context = {
        'title': title,
        'post': post,
        'post_count': post_count,
        'form': form,
        'comments': comments,
        'followers': followers
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    title = 'Создание новой публикации'
    if request.method != 'POST':
        form = PostForm()
        context = {'form': form, 'title': title}
        return render(request, template, context)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author)
    context = {'form': form, 'title': title}
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    title = 'Редактирование публикации'
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    if request.method != 'POST':
        form = PostForm(instance=post)
        context = {'form': form, 'title': title, 'is_edit': True}
        return render(request, template, context)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {'form': form, 'title': title, 'is_edit': True}
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    title = 'Избранные авторы'
    description = 'На странице отображаются авторы на которых вы подписаны'
    posts = Post.objects.filter(author__following__user=request.user).all()
    paginator = Paginator(posts, s.NUMBER_SHOW)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': title,
        'description': description,
        'page_obj': page_obj
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    if request.user.username == username:
        return redirect('posts:profile', username=username)
    following = get_object_or_404(User, username=username)
    Follow.objects.get_or_create(user=request.user, author=following)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    following = get_object_or_404(User, username=username)
    follower = get_object_or_404(Follow, author=following, user=request.user)
    follower.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% load user_filters %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {{ title }}
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}
          <form method="post" enctype="multipart/form-data"
          {% if action_url %}
            action="{% url action_url %}"
          {% endif %}
          >

          {% csrf_token %}


          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %}
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
                {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label}}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Опубликовать
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="container py-5">
  <h1>{{ title }}</h1>
  <p>
  {{ description }}
  </p>
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author %}">все публикации пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <article>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}"
        {% endthumbnail %}
        <p>{{ post.text | linebreaksbr }}</p>
      </article>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
  {% if  post.group %}
  <p>
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  </p>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="container py-5">
  <h1>{% block header %}{{ group.title }}{% endblock %}</h1>
  <p>
  {{ group.description }}
  </p>
  <article>
  {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author %}">все публикации пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text | linebreaksbr }}</p>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
      </article>
      {% if  post.group %}
      <p>
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      </p>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="container py-5">
  <h1>{{ title }}</h1>
  <p>
  {{ description }}
  </p>
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author %}">все публикации пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <article>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}"
        {% endthumbnail %}
        <p>{{ post.text | linebreaksbr }}</p>
      </article>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
  {% if  post.group %}
  <p>
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  </p>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include  'posts/includes/paginator.html' %}
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}{{ title|truncatechars:30 }}{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
        <li class="list-group-item">
          Группа: {{ post.group }}
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
          </a>
        {% endif %}
        </li>
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span>{{ post_count }}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Подписчиков:  <span>{{ followers }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{post.text}}</p>
      {% if user.pk == post.author_id %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
          редактировать запись
      </a>
      {% endif %}
     {% include 'posts/includes/comments.html' %}
    </article>
  </div>
</div>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ title }}{% endblock %}
{% block content %}

<div class="container py-5">
  <div class="mb-5">
  <h1>Все публикации пользователя {{ author.get_full_name }}</h1>
  <h3>Всего публикаций {{ post_count }}</h3>
  <h4>Всего подписчиков {{ followers }}</h4>
  {% if request.user != author %}
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      > Отписаться </a>
    {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      > Подписаться </a>
    {% endif %}
  {% else %}
    <p>Это Ваш профиль</p>
  {% endif %}
  </div>
  <article>
    {% for post in page_obj %}
    <ul>
      <li>
        Автор: <a href="{% url 'posts:profile' post.author.username %}">{{ author.get_full_name }}</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text | linebreaksbr }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
  </article>
  {% if  post.group %}
  <p>
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  </p>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include  'posts/includes/paginator.html' %}
</div>

{% endblock content %}